"""Curated institutional program names used to seed autocomplete (UTPB-aligned, not exhaustive).

The reference list is duplicated into SQLite (`academic_program_names`) so the UI reads a
single canonical list from the database after first boot.
"""

# Alphabetically ordered for readability; SQLite will sort independently.
DEFAULT_UTPB_PROGRAM_NAMES: tuple[str, ...] = (
    "Accounting",
    "Art",
    "Art Education",
    "Biochemistry",
    "Biology",
    "Business Analytics",
    "Business Management",
    "Chemistry",
    "Communication",
    "Computer Science",
    "Construction Management",
    "Criminal Justice",
    "Cybersecurity",
    "Data Science",
    "Economics",
    "Electrical Engineering",
    "Emergency Management Leadership",
    "Energy Land Management",
    "Energy Sustainability",
    "English",
    "Environmental Science",
    "Exercise Science",
    "Finance",
    "Forensic Chemistry",
    "French",
    "General Education",
    "Geology",
    "Health Promotion",
    "History",
    "Industrial Automation",
    "Industrial Technology",
    "Information Systems",
    "Integrated Studies — Arts and Humanities",
    "Integrated Studies — Language and Literacy",
    "Integrated Studies — Social Science",
    "Interdisciplinary Sciences",
    "Kinesiology",
    "Management",
    "Marketing",
    "Mathematics",
    "Mechanical Engineering",
    "Medical Sciences",
    "Music",
    "Music Performance",
    "Nursing — Pre-Licensure BSN",
    "Nursing — RN-BSN Completion",
    "Occupational Therapy",
    "Petroleum Engineering",
    "Physics",
    "Political Science",
    "Psychology",
    "Public Accounting",
    "Reading",
    "Social Work",
    "Sociology",
    "Spanish",
    "Special Education — General Curriculum",
    "Sport Management",
    "Studio Art",
    "Supply Chain Management",
    "Teaching",
    "Theatre Arts",
)
